# Generated by Django 4.1.4 on 2023-01-18 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_profilemodel_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='user_image',
            field=models.ImageField(default='default.png', upload_to='media', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
