# Generated by Django 4.1.4 on 2023-01-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_profilemodel_user_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['-date_stamp']},
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='date_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
