# Generated by Django 4.1.4 on 2023-01-22 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_profilemodel_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='followers',
        ),
    ]
