# Generated by Django 4.1.4 on 2023-02-03 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0018_categoryfollower'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='blog.category'),
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('follower', 'following', 'category')},
        ),
    ]
