# Generated by Django 4.1.4 on 2023-02-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_follower_category_alter_follower_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(default='default.png', null=True, upload_to='media'),
        ),
    ]
