# Generated by Django 4.1.4 on 2023-02-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_commentmodel_parent_comment_replymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='followed_categories',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
