# Generated by Django 4.1.4 on 2023-02-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_profilemodel_followed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='followed_categories',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='blog.category'),
        ),
    ]
