# Generated by Django 4.1.4 on 2023-02-09 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0025_alter_profilemodel_followed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='followers_c',
            field=models.ManyToManyField(related_name='followed_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
