# Generated by Django 4.1.4 on 2023-02-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_remove_category_followers_c_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryfollower',
            name='followers_c',
        ),
    ]
